fix: add more debugging

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -269,9 +269,10 @@ jobs:
           BASE64_PAYLOAD=$(echo -n $PAYLOAD | openssl base64 -A | tr -d '\n=' | tr '/+' '_-')
           JWT_HEADER_PAYLOAD="${BASE64_HEADER}.${BASE64_PAYLOAD}"
           JWT=$(echo -n "$JWT_HEADER_PAYLOAD" | openssl dgst -sha256 -sign app.pem | openssl base64 -A | tr -d '\n=' | tr '/+' '_-')
+          echo "::add-mask::$JWT"
 
-          echo "Decoded JWT Header: $(echo $JWT | cut -d '.' -f1 | base64 -d)"
-          echo "Decoded JWT Payload: $(echo $JWT | cut -d '.' -f2 | base64 -d)"
+          echo "Decoded JWT Header: $(echo "$JWT" | cut -d '.' -f1 | base64 -d || echo "Invalid header")"
+          echo "Decoded JWT Payload: $(echo $JWT | cut -d '.' -f2 | base64 -d || echo "Invalid payload")"
 
           # Get installation ID
           RESPONSE=$(curl -s -X GET \
